### PR TITLE
Adding support for Dark Mode.

### PR DESCRIPTION
**Pull request by KSTARK007**
I love this webpage. Thank you so much for creating it.

All I thought was, we could add a dark mode toggle to it and that is exactly what I did in this Pull Request.

Adding a screenshot for your reference.

The color scheme is similar to the wordle webpage. 

Screenshot 2022-01-30 at 3 38 49 AM

Screenshot 2022-01-30 at 3 39 05 AM

### CODE REVIEW

**Comment by qneill-sifive** [comment]
+1

**Comment by qneill** [comment]
+1!

**Comment by sadmoody** [comment]
Not sure why I never allowed this - must have slipped off my notifications but thanks for the ping @qneill and thanks for the pull request @KSTARK007

**Comment by KSTARK007** [comment]
Thank you @sadmoody!!

**Pull request merged**
